version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - vitas-network

  redis1:
    image: redis:7-alpine
    container_name: redis1
    hostname: redis1
    command: >
      redis-server
      --appendonly yes
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --bind 0.0.0.0
      --port 6379
      --protected-mode no
      --requirepass password
      --masterauth password
    ports:
      - "6379:6379"
      - "16379:16379"   # cluster bus
    volumes:
      - ./data/redis1:/data
    networks:
      - vitas-network

  redis2:
    image: redis:7-alpine
    container_name: redis2
    hostname: redis2
    command: >
      redis-server
      --appendonly yes
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --bind 0.0.0.0
      --port 6379
      --protected-mode no
      --requirepass password
      --masterauth password
    ports:
      - "6380:6379"
      - "16380:16379"
    volumes:
      - ./data/redis2:/data
    networks:
      - vitas-network

  redis3:
    image: redis:7-alpine
    container_name: redis3
    hostname: redis3
    command: >
      redis-server
      --appendonly yes
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --bind 0.0.0.0
      --port 6379
      --protected-mode no
      --requirepass password
      --masterauth password
    ports:
      - "6381:6379"
      - "16381:16379"
    volumes:
      - ./data/redis3:/data
    networks:
      - vitas-network

networks:
  vitas-network:
    driver: bridge
